workspace = { members = ["macros"] }


[package]
name = "bevy_test_helper"
version = "0.2.0"
edition = "2024"


[dependencies]
bevy = { version = "0.17.0-dev", git = "https://github.com/bevyengine/bevy.git", default-features = false }
serde = { version = "1", features = ["derive"], optional = true }
bevy_test_helper_macro_impl = { path = "macros" }

[features]
default = []
serde = ["dep:serde"]
